#!/bin/sh

#########################################
# Bridging script for IDS sensor	#
# SURFnet IDS		                #
# Version 1.02.04                       #
# 14-08-2006		                #
# Jan van Lith & Kees Trippelvitz	#
# Modified by Peter Arts                #
#########################################

#########################################################################################
# Copyright (C) 2005 SURFnet                                                            #
# Authors Jan van Lith & Kees Trippelvitz                                               #
# Modified by Peter Arts                                                                #
#                                                                                       #
# This program is free software; you can redistribute it and/or                         #
# modify it under the terms of the GNU General Public License                           #
# as published by the Free Software Foundation; either version 2                        #
# of the License, or (at your option) any later version.                                #
#                                                                                       #
# This program is distributed in the hope that it will be useful,                       #
# but WITHOUT ANY WARRANTY; without even the implied warranty of                        #
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the                         #
# GNU General Public License for more details.                                          #
#                                                                                       #
# You should have received a copy of the GNU General Public License                     #
# along with this program; if not, write to the Free Software                           #
# Foundation, Inc., 51 Franklin Street, Fifth Floor, Boston, MA  02110-1301, USA.       #
#########################################################################################

# This script is started by OpenVPN when the tunnel comes up.

#####################
# Changelog:
# 1.02.04 Disabled STP for the bridge and fixed pump bug
# 1.02.03 Changed pump to run on the bridge instead of the eth interface
# 1.02.02 Initial release
#####################

################
# Variables    #
################
basedir="/cdrom/scripts"
. $basedir/scripts.conf

################
# Start script #
################
# Check which interface is active
NETDEVICES="$(awk -F: '/eth.:|tr.:/{print $1}' /proc/net/dev )"
for DEVICE in $NETDEVICES
do
  active=`ifconfig $DEVICE | grep -i "RUNNING" | wc -l`
  ipcheck=`ifconfig $DEVICE | grep -i "inet addr" | wc -l`
  if [ $active = 1 ] && [ $ipcheck = 1 ]; then
    eth=$DEVICE
    break
  fi
done

# Check if the bridge is up or not.
checkbr=`ip link show up | grep $br | wc -l`
if [ $checkbr = 1 ]; then
  echo -e "${YELLOW}Bridging does not have to be started.${NORMAL}"
  exit
else
  # Check for static of dynamic network connection
  ifmethod=`cat $basedir/network_if.conf | grep -i "Method: " | cut -f2 -d: | cut -f2 -d " "`
  
  # Get the interface info.
  if [ $ifmethod  == "dhcp" ]; then
    echo -e "${YELLOW}Using DHCP networking, getting configuration from pump.${NORMAL}"
    eth_ip=`pump -i $eth --status | grep -i "IP: " | cut -f2 -d: | cut -f2 -d " "`
    eth_netmask=`pump -i $eth --status | grep -i "Netmask: " | cut -f2 -d: | cut -f2 -d " "`
    eth_broadcast=`pump -i $eth --status | grep -i "Broadcast: " | cut -f2 -d: | cut -f2 -d " "`
    eth_gw=`pump -i $eth --status | grep -i "Gateway: " | cut -f2 -d: | cut -f2 -d " "`
  else
    eth_ip=`cat $basedir/network_if.conf | grep -i "IP_sensor: " | cut -f2 -d: | cut -f2 -d " "`
    eth_netmask=`cat $basedir/network_if.conf | grep -i "Netmask: " | cut -f2 -d: | cut -f2 -d " "`
    eth_broadcast=`cat $basedir/network_if.conf | grep -i "Broadcast: " | cut -f2 -d: | cut -f2 -d " "`
    eth_gw=`cat $basedir/network_if.conf | grep -i "Gateway: " | cut -f2 -d: | cut -f2 -d " "`
  fi

  # Setup bridge.
  brctl addbr $br
  brctl addif $br $eth
  brctl addif $br $tap
  brctl stp $br off

  # Starting pump for the bridge interface
  checkpump=`ps -ef | grep -i pump | grep -v grep | wc -l`
  if [ $checkpump -ge 1 ]; then
    killall pump
  fi
  pump -i $br 2>/dev/null

  # Setup interfaces.
  if [ $enable_promisc -eq 1 ]; then
    ifconfig $eth 0.0.0.0 promisc up
    ifconfig $tap 0.0.0.0 promisc up
  else
    ifconfig $eth 0.0.0.0 -promisc up
    ifconfig $tap 0.0.0.0 -promisc up
  fi
  ifconfig $br $eth_ip netmask $eth_netmask broadcast $eth_broadcast
  route add -net default gw $eth_gw
fi
